### PR TITLE
Hevc cabac

### PR DESCRIPTION
**Pull request by dingo9**

### CODE REVIEW

**Comment by mraulet** [comment]
was it intended?

**Comment by dingo9** [comment]
no, sorry....

I've done some work in HM for parallel decoding in frame(without wpp), the key point is decode CABAC first, and scheduling cu decode order into different pipe line. I want to add such feature into openHEVC and I found your team‘s working. When I checkout the source code, I done some stupid operate.

English is not my native language, sorry for grammar mistake

**Comment by mraulet** [comment]
I will close the ticket then. you are welcome to do it hevc_cabac. This branch does have cabac in parallel of the rest of the CTB. you just have to add the pseudo wpp on the decoding of the CTB. Did you think of any gain? The problem I can see is related to a real bottleneck in the cabac, not really in the decoding process of the ctb itself. 
__
Mickaël

**Comment by dingo9** [comment]
ok, please close it~

**Pull request closed without merging**
